language: c
os:
    - osx
    - linux

install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then sudo apt-get install libopenblas-dev liblapack-dev ocl-icd-opencl-dev libproj-dev ; fi

script:
    - cmake .
    - make
    - ./test/projcl_test
