language: c
os:
    - osx
    - linux

before_script:
    - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then sudo apt-get install libblas-dev liblapack-dev ; fi

script:
    - cmake .
    - make
    - ./test/projcl_test
