language: c
os:
    - osx
    - linux

addons:
    apt:
        packages:
            - libblas-dev
            - liblapack-dev
            - ocl-icd-opencl-dev
            - libproj-dev
            - alien

install:
    - cat /proc/cpuinfo

script:
    - cmake .
    - make
    - ./test/projcl_test -CPU
