language: c
os:
    - osx
    - linux

addons:
    apt:
        packages:
            - libblas-dev
            - liblapack-dev
            - ocl-icd-opencl-dev
            - libproj-dev

install:
    - ./.travis/install.sh

script:
    - cmake .
    - make
    - ./test/projcl_test -CPU
