language: c
sudo: required
matrix:
    include:
        - os: linux
          dist: trusty
        - os: osx
          osx_image: xcode6.4
        - os: osx
          osx_image: xcode7.3
        - os: osx
          osx_image: xcode8.3

addons:
    apt:
        packages:
            - libblas-dev
            - liblapack-dev
            - ocl-icd-opencl-dev
            - alien

install:
    - ./.travis/install-proj4.sh
    - ./.travis/install-opencl.sh

script:
    - cmake .
    - make
    - ./test/projcl_test -CPU
